- name: "Unsplash"
  url: "https://unsplash.com"
  search_url: "https://unsplash.com/search/"
- name: "Picjumbo"
  url: "https://picjumbo.com"
  search_url: "https://picjumbo.com/?s="
- name: "StockSnap.io"
  url: "https://stocksnap.io"
  search_url: "https://stocksnap.io/search/"
- name: "Negative Space"
  url: "https://www.negativespace.co"
  search_url: "https://www.negativespace.co/?s="